const en = {};
en.LEARN = "Learn";
en.ABOUT = "About";
en.GET_INVOLVED = "Get Involved";
en.OUR_STORY = "Our Story";
en.DASHBOARD = "Dashboard";
en.STATEPARTNER = "State Partners";
en.SWITCH_VIEWS = "Switch Views";
en.SWITCH_TO_VIEW = "Switch to %1 View";
en.STUDENT = "Student";
en.VOLUNTEER = "Volunteer";
en.ADMIN = "Admin";
en.PARTNER = "Partner";
en.STUDENTS = "Students";
en.VOLUNTEERS = "Tutors";
en.PARTNERS = "Partners";
en.DONATE = "Donate";
en.VOLUNTEER_WITH_US = "Volunteer with Us";
en.MERAKI_TEAM = "Meraki Team";
en.MENTOR = "Mentor";
en.SCRATCH = 'Scratch';
en.NAVGURUKUL_ADMISSION = "Navgurukul Admission";
en.OPPORTUNITIES = "Opportunities";
en.CLASSES = "Classes";
en.SEARCH_FOR_COURSES = "Search for Courses...";
en.CAREERS = "Careers";
en.PROFILE = "Profile";
en.LOGOUT = "Logout";
en.TUTOR = "Tutor";
en.CERTIFICATE_COMPLETION_WARNING =
  "Please complete all the courses to unlock %1 certificate";

export default en;
