export const types = {
  GET_PROGRESS_TRACKING_INTENT: "GET_PROGRESS_TRACKING_INTENT",
  GET_PROGRESS_TRACKING_INTENT_RESOLVED:
    "GET_PROGRESS_TRACKING_INTENT_RESOLVED",
  GET_PROGRESS_TRACKING_INTENT_REJECTED:
    "GET_PROGRESS_TRACKING_INTENT_REJECTED",

  // GET_PATHWAY_INTENT: "GET_PATHWAY_INTENT",
  // GET_PATHWAY_INTENT_RESOLVED: "GET_PATHWAY_INTENT_RESOLVED",
  // GET_PATHWAY_INTENT_REJECTED: "GET_PATHWAY_INTENT_REJECTED",

  // GET_PATHWAY_COURSE_INTENT: "GET_PATHWAY_COURSE_INTENT",
  // GET_PATHWAY_COURSE_INTENT_RESOLVED: "GET_PATHWAY_COURSE_INTENT_RESOLVED",
  // GET_PATHWAY_COURSE_INTENT_REJECTED: "GET_PATHWAY_COURSE_INTENT_REJECTED",

  // GET_UPCOMING_BATCHES_INTENT: "GET_UPCOMING_BATCHES_INTENT",
  // GET_UPCOMING_BATCHES_INTENT_RESOLVED: "GET_UPCOMING_BATCHES_INTENT_RESOLVED",
  // GET_UPCOMING_BATCHES_INTENT_REJECTED: "GET_UPCOMING_BATCHES_INTENT_REJECTED",

  // GET_UPCOMING_ENROLLED_CLASSES_INTENT: "GET_UPCOMING_ENROLLED_CLASSES_INTENT",
  // GET_UPCOMING_ENROLLED_CLASSES_INTENT_RESOLVED:
  //   "GET_UPCOMING_ENROLLED_CLASSES_INTENT_RESOLVED",
  // GET_UPCOMING_ENROLLED_CLASSES_INTENT_REJECTED:
  //   "GET_UPCOMING_ENROLLED_CLASSES_INTENT_REJECTED",

  // GET_ENROLLED_BATCHES_INTENT: "GET_ENROLLED_BATCHES_INTENT",
  // GET_ENROLLED_BATCHES_INTENT_RESOLVED: "GET_ENROLLED_BATCHES_INTENT_RESOLVED",
  // GET_ENROLLED_BATCHES_INTENT_REJECTED: "GET_ENROLLED_BATCHES_INTENT_REJECTED",
};

export const actions = {
  getProgressTracking(data) {
    return {
      type: types.GET_PROGRESS_TRACKING_INTENT,
      data,
    };
  },
  getProgressTrackingResolved(data) {
    return {
      type: types.GET_PROGRESS_TRACKING_INTENT_RESOLVED,
      data,
    };
  },
  getProgressTrackingRejected(error) {
    return {
      type: types.GET_PROGRESS_TRACKING_INTENT_REJECTED,
      error,
    };
  },
};
