# This is a basic workflow to help you get started with Actions
# https://dev.to/achukka/build-and-test-react-app-with-github-actions-2jb2

name: Build and Test React App

# Controls when the workflow will run
on:
  # Triggers the workflow on push (to given branches) or pull request events
  push:
    branches: ["main", "dev", "classBatch", "chore-feat/header-refactoring-and-language-support"]
  pull_request:
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm install
          npm ci
          npm run build --if-present
          npm test
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CI: false
          REACT_APP_MERAKI_URL: "https://api.merakilearn.org/"
      # - name: deploy to gh-pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #    publish_dir: ./build
      #    publish_branch: gh-pages
