export const AUTH_KEY = "__AUTH__";

export const PATHS = {
  HOME_PATH: "/",
  LOGIN: "/login",
  CLASS: "/class",
  COURSE: "/course",
  PYTHON_COURSE: "/python-course",
  JAVAXCRIPT_COURSE: "/javascript-course",
  TYPING_GURU: "/typing-guru",
  ENGLISH_COURSE: "/english-course",
  COURSE_CONTENT: "/course/:courseId",
  EXERCISE: "/exercise/:exerciseId",
  MENTOR: "/mentor",
  USER: "/user",
  PROFILE: "/Profile",
  PRIVACY_POLICY: "/privacy",
  AFE: "/amazon-future-engineer",
  PARTNERS: "/partner",
  PARTNER_DATA: "/partner/:partnerId",
  STUDENT: "/student/:studentId",
  OPPORTUNITIES: "/opportunities",
  NAVGURUKUL_INTRODUCE: "/navgurukul/:partnerId",
  ADMISSION: "/admission",
  REDIRECT: "/redirect",
  VOLUNTEER: "/volunteer",
  STATEPARTNER: "/state-dashboard/:clusterId",
  STATE: "/state-dashboard",
  VOLUNTEER_OVERVIEW: "/volunteer/:volunteerId",
};
